component_depth: 8

languages:
  - name: cpp
    
    production:
      include:
        - /src/*.cpp
        - /src/*.h
        - /src/*.inl
      exclude:
        - /src/tests/.*

    test:
      include:
        - /src/tests/.*