os: linux
sudo: require
language: cpp
compiler: gcc
dist: trusty

env:
  global:
   - secure: "AgHX8cRVKqLXZS7HKK4W0C0MnVu3eUioNlbMvvvpDobJR5st0nxNSQz7dLN0EcLbbvJlAFGQl1rg9zo+Z4DvrHDX5sn3We8UPt4EMC1qmVyPvpMaai0cQ+lDpIj0VsumqsdfWE2z+ALdkQ0irNrk7Bavz7kKgnhDDIaZFm93QuXwE0zYhg4PABe/XdFt6ZGVwXEUUXUr05fDhNbAF34JFhejt9+JxKlrDoY5EKlERFtFHPVtEanm/m8MCkptT2ozwilqAJ9mYSlUtyMzVVpcvlIl7SPVfz9JW85hPGDonEZQlTxIvdoDFlqw1bxlqCSy4q4AJVpHFI/0KGk0F1eis1cOXkMstOAoyPsREekBATNTikvm7gglnFuWSP0vkvRqnnmk6HoxQcgJ43079ADFx9MHFWCljhJ6GtJVW5Mysbsj57ipaRAQyADHC2Ckk6o22SDjF4GhncsoJ4qHYJZbvig7b5nsyb/kQODKagi075oG2ZPjy6TvC7iAY6c4YHkh92DZqZ9myRC5d8tiiNsssQXVBq5jC5MySzfoeOOJhCJkPXogvM6bWTCjxDSAjCMeCa3hXYJmAZ1wo3vFFzSYybT3h17gC8pJHxZoIb4XxPybdHk1sc0dvEWhjSQqIicZ+Cw7514x5Qh/SsBVhk3YYOjRu8Qmbu8fL+37bMJwYHA="

branches:
  only:
  - master

addons:
  apt:
    packages: libboost-all-dev
    coverity_scan:
      project:
        name: "timcogames/Sway.Framework"
      notification_email: victor-timoshin@hotmail.com
      build_command_prepend: "cov-configure --comptype gcc --compiler gcc-5"
      build_command: "make VERBOSE=1"
      branch_pattern: coverity_scan

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script:
  - make
  - ./tests
  - sudo bash ./codecov.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false