os: linux
sudo: require
language: cpp
compiler: gcc
dist: trusty

env:
  global:
  # COVERITY_SCAN_TOKEN
   - secure: "TgL2meQ5Xi6dFG5GhrGI92qjZaHEqplIiuX628BFy92cU+Tu59xzDE8FeJg+twDOk08frpVNciuJoCbg8FI5R5ex4ZJN1QKgti93QwYQODDG2EntFrQqtiLGNTaqA/uN1vKBcj6uRSg3JScyxs4MvcuJFfociiB/OY0AXCv5YwCSO9vhJzZRowcUT2bM1FcLkLa5fU6ebvJxw/mAW4H6jCfvoFdhm9ir63/zhihAtNUhpLMeTppJv+6VjA6uX0JjFHyZZpT7dHDZc63LfAp2wtKMpJB7xE/lNOFwO+gwkhkrsJsOkgVKlcl9TZ5vgYocBt6UsgiKV66F6hvfp9d/7nm+FWDxWIKkKiFib+azVy9zZIEtPaRLJkkKqUZWFyfOxrtC2yoGMk8rTwPuO+TuTNKyQ+B6wh5anLOBBsWAn/HAqTWZ+e2AaWhf2LLxp7AJ8LA1kHPb4xQ+WvsJaftmEtDdgaKr+8Hdvy2aLm7IGNrlAWGePNUaXbtywKPJejcKu5JkPxc/bYLGC68ZlwIj9u4/RMw4K1OqGnEApLfRdcoNYIRgBpCaKQ+iAIlKgwleffNW6uXcPSRTovztK9iNHT0vbfiMjpo0zew7ngFpK5qBm7il0K7Q2nYUtenZl9EMh3DBtHBwP/ut5Ynabubc8kUANP1vXRpb/LXHwpLDH64="

branches:
  only:
  - master

addons:
  apt:
    packages: libboost-all-dev
    coverity_scan:
      project:
        name: "timcogames/Sway.Framework"
      notification_email: victor-timoshin@hotmail.com
      build_command_prepend: "./configure"
      build_command: "make"
      branch_pattern: master

before_install:
  - sudo echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script:
  - make
  - ./tests
  - sudo bash ./codecov.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false