#ifndef SWAY_GL_EXTENSIONS_H
#define SWAY_GL_EXTENSIONS_H

#include "glprereqs.h"

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(gl)

class Extensions {
public:
	static PFNGLGENBUFFERSARBPROC glGenBuffersARB;
	static PFNGLBINDBUFFERARBPROC glBindBufferARB;
	static PFNGLBUFFERDATAARBPROC glBufferDataARB;
	static PFNGLGETBUFFERPARAMETERIVARBPROC glGetBufferParameterivARB;
	static PFNGLDELETEBUFFERSARBPROC glDeleteBuffersARB;
	static PFNGLISBUFFERARBPROC glIsBufferARB;
	static PFNGLBUFFERSUBDATAARBPROC glBufferSubDataARB;
	static PFNGLMAPBUFFERARBPROC glMapBufferARB;
	static PFNGLUNMAPBUFFERARBPROC glUnmapBufferARB;

	static PFNGLCREATEPROGRAMOBJECTARBPROC glCreateProgramObjectARB;
	static PFNGLCREATESHADEROBJECTARBPROC glCreateShaderObjectARB;
	static PFNGLSHADERSOURCEARBPROC glShaderSourceARB;
	static PFNGLCOMPILESHADERARBPROC glCompileShaderARB;
	static PFNGLATTACHOBJECTARBPROC glAttachObjectARB;
	static PFNGLLINKPROGRAMARBPROC glLinkProgramARB;
	static PFNGLUSEPROGRAMOBJECTARBPROC glUseProgramObjectARB;
	static PFNGLGETUNIFORMLOCATIONARBPROC glGetUniformLocationARB;
	static PFNGLDELETEPROGRAMSARBPROC glDeleteProgramsARB;
	static PFNGLDETACHOBJECTARBPROC glDetachObjectARB;
	static PFNGLDELETEOBJECTARBPROC glDeleteObjectARB;
	static PFNGLVALIDATEPROGRAMARBPROC glValidateProgramARB;
	static PFNGLUNIFORM4FARBPROC glUniform4fARB;
	static PFNGLGETPROGRAMIVARBPROC glGetProgramivARB;
	static PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
	static PFNGLGETSHADERIVPROC glGetShaderiv;
	static PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
	static PFNGLGETOBJECTPARAMETERIVARBPROC glGetObjectParameterivARB;
	static PFNGLGETINFOLOGARBPROC glGetInfoLogARB;

	static PFNGLDISABLEVERTEXATTRIBARRAYARBPROC glDisableVertexAttribArrayARB;
	static PFNGLGETATTRIBLOCATIONARBPROC glGetAttribLocationARB;
	static PFNGLVERTEXATTRIBPOINTERARBPROC glVertexAttribPointerARB;
	static PFNGLENABLEVERTEXATTRIBARRAYARBPROC glEnableVertexAttribArrayARB;	

	static void define();
};

NAMESPACE_END(gl)
NAMESPACE_END(sway)

#endif // SWAY_GL_EXTENSIONS_H