#ifndef SWAY_PLATFORM_UNIX_GLX11_ATOMS_H
#define SWAY_PLATFORM_UNIX_GLX11_ATOMS_H

#include "glx11prereqs.h"

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(glx11)

enum Atoms
{
	kAtom_NET_WM_STATE,
	kAtom_NET_WM_STATE_MAXIMIZED_VERT,
	kAtom_NET_WM_STATE_MAXIMIZED_HORZ,
	kAtom_NET_WM_STATE_FULLSCREEN,
	kAtom_WM_DELETE_WINDOW,
	kAtom_COUNT
};

NAMESPACE_END(glx11)
NAMESPACE_END(sway)

#endif // SWAY_PLATFORM_UNIX_GLX11_ATOMS_H